run_id: cart_pole
algo: ppo
cuda: True
max_step: 10000000
batch_size: 200
buffer_size: 2000
env:
    env_name: CartPole-v0
    seed: 309
    num_process: 4
    normalize: True
model:
    type: t1
    params:
        hidden_unit: 128
        gamma: 0.99
        lambda: 0.95
        lr: 0.0007
        eps: 0.2
        epoch: 3
        c_entropy: 0.01
        c_value: 0.5
extrinsic:
    strength : 1.0
    gamma : 0.99
log_interval: 10
save_interval: 100